# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @useDynLib detectRUNS
#' @importFrom Rcpp sourceCpp
#' @export
timesTwo <- function(x) {
    .Call('detectRUNS_timesTwo', PACKAGE = 'detectRUNS', x)
}

