# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert 0/1/2 genotypes to 0/1
#'
#' This is a utility function, that convert 0/1/2 genotypes (AA/AB/BB) into 0/1
#' (either homozygous/heterozygous)
#'
#' @param genotype vector of 0/1/2 genotypes
#'
#' @return converted vector of genotypes (0/1)
#' @export
#'
#' @examples
#' geno012 <- c(1, 2, 0, 1, NA, 2, 0, NA)
#' geno01 <- genoConvert(geno012)
#' @useDynLib detectRUNS
#' @importFrom Rcpp sourceCpp
#' @export
genoConvertCpp <- function(genotype) {
    .Call('detectRUNS_genoConvertCpp', PACKAGE = 'detectRUNS', genotype)
}

#' Function to return a vector of T/F for whether a SNP is or not in a RUN
#'
#' This is a core function. The function to determine whether a SNP is or not in a RUN.
#' The ratio between homozygous/heterozygous windows and total n. of windows is computed here
#'
#' @param RunVector vector of TRUE/FALSE (is a window homozygous/heterozygous?)
#' @param window size of window (n. of SNP)
#' @param threshold threshold to call a SNP in a RUN
#'
#' @return vector of TRUE/FALSE (whether a SNP is in a RUN or NOT)
#'
#' @examples #not yet
#' @useDynLib detectRUNS
#' @importFrom Rcpp sourceCpp
#' @export
snpInRunCpp <- function(RunVector, window, threshold) {
    .Call('detectRUNS_snpInRunCpp', PACKAGE = 'detectRUNS', RunVector, window, threshold)
}

